### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by rmatsum836**
This is a continuation of #21, mostly addressing Justin's requested changes.

### CODE REVIEW

**Comment by rmatsum836** [comment]
I had trouble passing the Gromacs regression tests while building the docker image so I may ask @rsdefever or @justinGilmer to try building locally and upload to docker hub.  Do the current changes look okay?

**Comment by justinGilmer** [comment]
Building now, will let you know

**Comment by rmatsum836** [comment]
Putting this here for reference: https://github.com/docker/build-push-action/issues/100

**Comment by justinGilmer** [comment]
All the regression tests passed for me! So i think this is good to go!

**Review by justinGilmer — APPROVED** [review]

**Comment by rmatsum836** [comment]
Now have a working GitHub Action to build and push the image to docker hub.

**Pull request merged**
